---
repository_name: 'essnapshot'
# the hash must represent the JSON body sent to ES
# see https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html
repository:
  type: 'fs'
  settings:
    location: '/mnt/snapshot'
    compress: 'true'
# retention time of 7 days
retention_time: '7d'

